site_name: Tin docs
site_url: https://randomusert-s-mods.github.io/tin-docs/
site_description: Documentation for Tin mods by Randomusert
site_author: Randomusert


repo_url: https://github.com/randomusert-s-mods/tin-docs
edit: blob/main/docs/

# Theme
theme:
  name: readthedocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: true


# Nav
nav:
  - Home: index.md
  - Mods:
      - Tincore: tincore/index.md


# copyright
copyright: Copyright (c) 2026 Randomusert. Licensed under the MIT License.